# Data paths
ffhq_path: "./data/ffhq/"
danbooru_path: "./data/anime_portraits/"

# Other paths
checkpoint_path: "./checkpoints"
output_path: "./outputs"
pretrain_stylgan_path: "./pretrain/Gs.pth"
pretrain_resnet_path: "./pretrain/20180402-114759-vggface2.pt"

# Save path
save_path: "./checkpoints/pretrained_adapter.pth"
out_ffhq_img_path: "./outputs/frankenstein_ffhq.png"
out_anime_img_path: "./outputs/frankenstein_anime.png"

# Model settings
model_name: "Pre-trained StyleGAN-2 Adapter"

# Hyperparameters
lr: 0.0001
batch_size: 10
