# Data paths
ffhq_path: "./data/ffhq/"
danbooru_path: "./data/anime_portraits/"

# Other paths
checkpoint_path: "./checkpoints"
output_path: "./outputs"
pretrain_stylgan_path: "./pretrain/Gs.pth"

# Model settings
model_name: "Pre-trained StyleGAN-2 Adapter"

# Hyperparameters
lr: 0.1
batch_size: 32
